CREATE TABLE IF NOT EXISTS `Workers` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `CN` varchar(100) NOT NULL,
  `ADDR` varchar(100) NOT NULL,
`EMAIL` varchar(100) NOT NULL,
  `COMPANY_POSITION` varchar(100) NOT NULL,
    `DEPARTMENT` varchar(100) NOT NULL,
  `PAY` int NOT NULL,
  `PAYC` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;