CREATE TABLE IF NOT EXISTS `FOOD_ID` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `INGREDIENTS` varchar(100) NOT NULL,
  `PRICE` float NOT NULL,
  `QTY_IN` int(11) NOT NULL,
  `QTY_UNIT` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;