USE inventory;
CREATE TABLE IF NOT EXISTS `Bundles` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `BUNDLE` varchar(100) NOT NULL,
  `PRICE_TOTAL` float NOT NULL,
  `NUM_G` int NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;