
CREATE TABLE IF NOT EXISTS `inventory` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM` varchar(100) NOT NULL,
  `QTY_IN` int(11) NOT NULL,
  `QTY_OUT` int(11) NOT NULL,  
  `QTY_CNST` int(11) NOT NULL,
  `QTY_UNIT` varchar(100) NOT NULL,
  `PRICE_BUY` int(11) NOT NULL,
  `PRICE_SELL` int(11) NOT NULL,
  `CAT` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;